# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_description', models.TextField(max_length=1000)),
            ],
        ),
    ]
